### ISSUE TITLE
Manage GUI structure and helptexts

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#119]
### Feature Description

Create management system to communicate new GUI features and helptexts among researchers and programmers. 

Used to be a word-document but this is not ideal:
https://sourceforge.net/p/pspm/svn/HEAD/tree/development/Developers%20Documents/Structure%20GUI.docx

All help texts are also part of the lyx-manual. However, the GUI structure is not clearly visible there.

a related issue is #23

**Comment by teddychao** [comment]
@dominikbach I think a final version can be delivered to researchers and programmers as PDF with index at the beginning. This word document seems a little confusing to me as the tables do not have header. Would you mind if I design a sample and show it to you? LaTeX is my best friend but I do not mind to use another software to produce if I need to...

**Comment by teddychao** [comment]
I am not sure the current conversion from Lyx to LaTeX is reliable. It generates sentences like this, which should not be used. I am not sure if we can use LaTeX as the source and convert it to Lyx for modification, because such mistakes can be avoided...
![image](https://user-images.githubusercontent.com/3895146/122306270-0b367500-cf00-11eb-8b34-0273f80b27a9.png)

**Comment by teddychao** [comment]
We discussed in a recent PsPM users' group meeting about this issue. We agree this is important but we may spend more time on it eg more than 2 months. Thus I include it in v6.1.

**Comment by dominikbach** [comment]
This is fixed now. All GUI items call the function help texts, and these are documented on https://bachlab.github.io/PsPM/ref/
