### ISSUE TITLE
DCM Time Windows and Trial-Wise Predicted Time Series

### ISSUE THREAD

**Issue by pdeming** [bachlab/PsPM#123]
### Summary

Hi, I have a conceptual question based on the output of pspm_dcm. I'm modeling SCR during a task in which participants watched 6s videos of people making facial expressions of emotion. After each video participants responded to three self-timed rating screens, followed by a 1s fixation screen, so ITIs are variable (but are generally ~15-20s). I specified the 6s between video onset and offset as the event window in DCM. 

When I plot the predicted and observed SCR by trial using pspm_review, I notice that predicted SCRs are usually modeled 10-20s after video onset, which is outside the event window (example below, 10Hz). Is it correct that, although the modeled SCR tends to occur during the rating screen rather than during the video, the amplitude estimated by the model corresponds to SN activity during the event window (in response to the video)?

![dcm_scr_trials](https://user-images.githubusercontent.com/67028073/84834717-b06df300-aff7-11ea-9e0a-f541bf23556a.png)

Also, I'm wondering if it's possible and advisable to extract the predicted time series for each trial (corresponding to the red lines in the plots above). Ideally, I could use the predicted time series to plot out an average predicted time series for each trial type (anger, disgust, etc.), for individual participants as well as for groups of participants (e.g., patient vs. control). I dug around in the DCM output but didn't find anything corresponding to the trial-wise predicted time series.

Thanks!
Phil

### Technical Info
* PsPM revision ID: 4.2.1
* MATLAB version: R2019a

**Comment by dominikbach** [comment]
Hi Phil. 

Thanks for reaching out.

The DCM review shows predicted & observed data from the beginning of one trial to the beginning of the next. I suspect that in your case, this includes the self-timed ratings. The x-axis is in samples at the default resolution of 10 Hz (unless you changed the downsampling rate when calling DCM), so that would correspond to the ITIs that you noted.

Inbetween trials, DCM models spontaneous fluctuations (again, unless you changed that in the inversion settings). SCR are often more pronounced during active motor behaviour so it's not unheard of that responses to a rating scale are larger than to passively viewed stimuli. 

So, what I suspect you are seeing here are responses to the rating scale. These are not part of the stats output (although they can be accessed if you were interested). 

To confirm my suspicion, I would have to look at data from an individual trial in the actual DCM model file.

Best
Dominik

**Comment by pdeming** [comment]
Thanks, Dominik. Your explanation makes sense. I did not change the downsampling rate or the default inversion settings. It sounds like I can be confident that the model is accounting for spontaneous fluctuations during the self-timed ratings, and not attributing those SCRs to the stimulus period. 

I'm unable to send the model file without approval from our IRB. However, would you be willing to point me to the data from individual trials in the DCM model file? I know the trial-wise amplitude, latency, and dispersion data are in dcm.names. Is there a place to find the predicted time series for individual time series?

Phil

**Comment by dominikbach** [comment]
Hi Phil

when you load the DCM model file, you will find, separately for each session (sn):
- for SF, the estimated peak times and amplitudes of the underlying neural activity in dcm.sn{sn}.sf
- for the entire session, the predicted data in dcm.sn{sn}.yhat and the observed data in dcm.sn{sn}.y
- for each trial (trl), the predicted data in sum(dcm.sn{1}.posterior(trl).muX([1 4 7], :)) and the observed data in dcm.sn{1}.indata{trl}

You can also look at the individual trials using the review manager, which accesses all of the above automatically.

Dominik
