### ISSUE TITLE
sound event detection issues: pspm_find_sounds.m

### ISSUE THREAD

**Issue by SerenXia** [bachlab/PsPM#127]
### Summary
When preprocessing sounds, a few sound events cannot be detected by PsPM
### Steps to Reproduce
1. after importing and trimming acq files, the following codes were used to preprocess sound (from pspm_pipeline_prepare_acq.m, attached in zip):
if any(strcmpi('emg', inarg.chan))
    % find theoretical startle probe channel as reference trigger channel
    [~,~,adata] = pspm_load_data(newfn);
    trigchannel = find(strcmpi(cellfun(@(x) x.header.chantype, adata, 'un', 0), 'marker') & ...
        cellfun(@(x) length(x.data), adata) == probeno);

    options = struct('channel_action', 'add', ...
        'diagnostics', true, ...
        'channel_output', 'corrected', ...
        'maxdelay', 0.5, ...
        'mindelay', 0, 'trigchannel',trigchannel);
    pspm_find_sounds(newfn, options);
    
end

### Expected Results
58 startle probes were written into files
58 sound events associated with a marker (startle probe) found.
### Actual Results
58 startle probes were written into files
54 sound events associated with a marker (startle probe) found.
some sound events were missing.
### Technical Info
* PsPM revision ID: PsPM v4.3.0
* MATLAB version: R2018b

P.S. the datafiles were too large to be uploaded here, please check slack

**Comment by Noldos** [comment]
There is some noise on the sound channel. if you increase option.threshold = 0.2 (it defaults to 0.1) it works fine. the threshold value  is the percentage of the maximum power in the signal that is used to differentiate sound from noise.

If you run into missing markers, you can use options.plot=true to see where the problem lies and debug from there.
