### ISSUE TITLE
Modelling shocks with DCM

### ISSUE THREAD

**Issue by ozika** [bachlab/PsPM#155]
Hi all, I have a question about correctly modelling shocks and subsequent SCRs that were picked up by EDA recording in the DCM model. 

#### Trial Structure 
Cue onset -> response time (up to 4s) -> ISI (1-2s) -> Outcome (shock/noshock, 1s) -> ITI (1-4s, mean=2)

#### Information 

- the EDA recording was done on the same hand as where shocks were delivered and the signal got directly picked up (very short 200ms burst) plus it produced an SCR
- the SCR evoked by the shocks on trial *t* is on average in its refractory period during cue onset on trial *t+1*, so it needs to be accounted for 
- I know the DCM inversion accounts for events happening on previous trials, but my question is what is the correct way to include them

#### Analysis
- I am interested in the **anticipatory** period between cue onset and 250ms before the outcome (it's about 2.5 s on average)
- so far, I modeled only that window, but my question is how to best incorporate the **second** SCR evoked by the shock delivery (which is on average much bigger)
- I create an event file with two columns, onset and offset for each event

#### Question
*Approach 1*
- to model the shocks, I simply include a window between the shock onset on trial *t* and the time of the next **outcome** => not next cue onset, because the previous SCR is still happening 
- how many partially/fully overlapping events does the model account for? 
- would the correct practical way be to simply have more events and keep track of the trial type to extract the amplitude, dispersion and peak latency estimates?

*Approach 2* 
- model only the window of interest between cue and outcome and include outcome on the previous trial in subsequent statistical analysis
- I think this approach is inferior because of the variable ITI

Thanks for any comments!
Ondrej

**Comment by dominikbach** [comment]
Hi Ondrej
sorry for the delay in responding - summer holiday time :)
SCR to electric shocks are relatively stereotypical - well-modelled with a constant-latency response (see e.g. our initial LTI paper in 2020: Bach, Flandin, Friston, Dolan, Int J Psychophys). I don't think you will gain much by modelling this as a "flexible" response with variable latency - although the latter would be slightly more realistic and better explain the data, it would probably also pick up more noise (artefacts and spontaneous EDA unrelated to the experiment). 

That is, I would suggest you follow your Approahc 1, but in the DCM, you have
- one two-column matrix for event 1: this is the onset-offset window for the anticipatory response
- one one-column vector for event 2: this is the time point of the electric shock. 

You can also add more events if you want to model more. There is no limit on this on the modelling side. There is a limit on the biophysical side (and this limit is common to any analysis approach): if there is more than around 1 event per 2 seconds, then responses become highly non-linear (e.g. see Gerster et al. 2018 Psychophysiology, based on intraneural stimulation data from Göteborg)

I agree that Approach 2 would be inferior.

Regarding the shock-induced artefacts, your best bet may be to exclude these epochs by 
- either setting them to NaN
- or creating an "missing epochs" file and passing it to DCM
- and making sure that the default DCM settings for artefact exclusion are used, which are: < 2 s duration - just ignore the data from these epochs but use a time-continuous underlying model; > 2 s duration - split data & model into separate sessions

To define these epochs, I would just use the periods of shock delivery, rather than an algorithm to detect them in the data.

Hope this helps.
Dominik

**Comment by ozika** [comment]
Thank you for the explanation.

This worked very well. There is no effect of previous trial now and the results also make intuitive sense (higher amplitude for CS+ than CS- for example). 

Best wishes, 
Ondrej
