### ISSUE TITLE
DCM - model reinforced trials

### ISSUE THREAD

**Issue by LisaWirz** [bachlab/PsPM#163]
Hi everybody

I have a design that requires me to model SCRs for all trials, including the reinforced trials.
My task looks as follows:
Picture presentation for 5 sec --> intertrial interval between 3.5 and 6.5 sec
A shock may occur after 4.8 sec. Since we use a reinforcement rate of 80%, I only have 4 unreinforced trials.
I already tried Autonomate and Ledalab, but it is very hard - if not impossible - to distinguish the anticipatroy responses from the unconditioned responses to the shocks. Looking at the data, I do observe that the response times can vary quite a bit, which is why I decided to  give PsPM a try. I ran the DCM model, but it looks like the SCRs for reinforced trials are very large (about 7x as large as the SCRs for all other trial types). SCRs for the 4 unreinforced trials are much smaller and do not differ from the CS- trials.

Do you think a DCM is suitable here and are there any options I can tweak to get a better result (I used the default values now).

Thanks in advance!

Cheers
Lisa

**Comment by irojkov-ph** [comment]
Hi Lisa,

Thank you very much for using our software and contacting us :relaxed: 
Unfortunately, I am not an expert in this but I can try answer your question anyway. Prof. Bach (@dominikbach) will be able to better advise you but he is currently away and will be available only from next week on.

Referring to the PsPM manual:
The DCM model for skin conductance (p. 80 in the manual) is powerfull when the response timing is unknown and has to be estimated such as for anticipatory SCR in fear conditioning. So if in your case this timing is known, a solution might be to consider a general linear model (GLM) for SCR (p.75 in the manual). If not, then as you've suggested, a solution could be to tune some parameters in the DCM. For you, the most suitable options to tweak are those related to the response function and inversion (p.84 in the manual). 

Sorry for not being of better help here :disappointed: 

Best,
Ivan

**Comment by dominikbach** [comment]
Hi Lisa

in my view, DCM is a good idea here as you don’t know the timing of the anticipatory burst. 

It would be important to model each trial event separately, but in the same way across experimental conditions. That is, if I understand your design correctly, you model a picture response per trial, and a US response per trial, for all trials. In other words, you model a US response even if there is no US, to avoid your model being biased by design. 

Whether the model is “good” can be evaluated by a contrast that is independent from your hypothesis. Also you can look at trial fits as a plausibility check. I’m not sure from what you write whether Your results are implausible. 

Without knowing whether there is a problem with the model, it is difficult to say how it could be improved. At the short ITIs however the model will not account for SF in ITIs unless you change the settings. 

Hope this helps
Dominik
