### ISSUE TITLE
 "GLM for SCR" Problem with event onsets/ nusiance file 

### ISSUE THREAD

**Issue by Maren186** [bachlab/PsPM#247]
### "GLM for SCR" Problem with event onsets/ nusiance file 

Hi,

I have an issue when trying to run the GLM for SCR with the batch editor. 
I finally imported my BrainVision data with PsPM and also imported the marker channel from my .vmrk file.
The structure of my data is:
Channel 1: SCR
Channel 2-4: EMG (startle)
Channel 5: ECG
Channel 6: Markers

I'm not quite sure whether the import of the markers worked as I wanted it to. Maybe you can check this with me?
However, my main problem is that I'm not sure how to define event onsets or a nusicance file. I have a .txt Dokument (exported from Psychopy) which might inlcude relevant information. Still, choosing this file as a nusiance file doesn't work either.
I would be very thankful if you could help me with my issue!
I have uploaded some example data and files here: https://drive.google.com/drive/folders/19s1UdPeB6JlfxcXB56clc2sA8DP2Yf_e?usp=sharing

Thank you very much and best regards,
Maren 

### Technical Info
* PsPM revision ID: PsPM_5.0.0
* MATLAB version: R2021a

![grafik](https://user-images.githubusercontent.com/72658453/122363354-284b6200-cf59-11eb-829b-a4726865f505.png)
![grafik](https://user-images.githubusercontent.com/72658453/122363432-38634180-cf59-11eb-82cd-96eec8575f73.png)

**Comment by SerenXia** [comment]
Hi Maren,

Currently I think nuisance file can be only used for pupillary analysis, e.g. using timecourse of luminance for pupil size analysis.

For SCR, you need to specify a condition file for GLM.

You can either generate a condition file (.mat) for each data file. The condition file should contain two variables:
"names": a cell array of string/characters for the names of the experimental conditions
"onsets": a cell array of number vectors for the onsets of events for each name specified in "names"

You can do this condition file either in a condition-wise manner or trial-wise manner (e.g. no condition in the experiment or we want to get estimates of each trial but not each condition).
Here is an example:
Condition-wise:
names = {'cond1', 'cond2', 'cond3'};
onsets = {[1,3,5,6,9],[2,4,8,10,11],[7,12,13,14,15]};

if you are using markers (i.e. trial onsets) as time units, then the above means:
trial 1.3,5,6,6,9 are condition 1, and trial 2,4,...11 are condition2, etc.

if you are using e.g. seconds as time units, then onsets should be in seconds :)

or we can generate a condition file in a trial-wise manner:
names = {'trl1', 'trl2', 'trl3'};
onsets = {[1], [2], [3]};

again if time units in seconds, onsets should be in seconds.

Instead of generating condition file, you can also choose "enter conditions manually" and just add your conditions one by one.
Or if your marker channel contains event onsets and names, you may select "define conditions from distinct values/names of event marker". There are some help texts in the batch editor when you click on each option :)


Regards,
Yanfang

**Comment by Maren186** [comment]
Hi Yanfang,

thank you very much! That makes perfectly sense.
I'll try to run the GLM with your information! :) 

Regards,
Maren
