### ISSUE TITLE
pspm_get_events should allow choosing rising, middle or falling edge of a marker

### ISSUE THREAD

**Issue by eozd** [bachlab/PsPM#31]
### Feature Description
Currently, `pspm_get_events` returns the middle of a marker impulse by default. However, this behaviour is undesirable in many situations where tagging the marker by the rising or the falling edge make more sense. Therefore, we should add an option to `pspm_get_events` so that the user can choose whether they want
1. rising edge
2. middle
3. falling edge

of a marker impulse.

In addition, this option should be cascaded all the way to the top user-level functions that at some point use `pspm_get_events`. Therefore, the main tasks are

* [x] Modify `pspm_get_events` to allow choosing the marker tag
* [x] Find top-level user space functions that depend on this functionality
* [x] Include the aforementioned option in these functions' interfaces.

**Comment by irojkov-ph** [comment]
I am going through all the issues right now in preparation for the future release.

@sammaxwellxyz, if you have some time can you have a look at this please ? I think it's pretty much done except that we should be able to select the 'flank' in the GUI. Currently it's not possible. It shouldn't be too difficult I guess since `pspm_get_events` is used only by `pspm_get_markers` and `pspm_get_hb` (so only two channel type are concerned by this option). It could be nice to include it in the new release.

**Comment by irojkov-ph** [comment]
This feature was implemented with #149  and added to the new release. I close it.
