### ISSUE TITLE
SCR and PSPM

### ISSUE THREAD

**Issue by Cosima24** [bachlab/PsPM#329]
### Technical Info
* PsPM revision ID:
* MATLAB version: R2021a

Good morning,

Is there anyone who is trained using pspm for SCR?
![Screenshot 2021-11-24 092224](https://user-images.githubusercontent.com/93911437/143209975-93aa18c4-e6e4-4f64-a1d7-dd2d936db7e8.png)
![Screenshot 2021-11-24 092224](https://user-images.githubusercontent.com/93911437/143209997-8a9d8021-ed48-462a-831f-c850715fbeee.png)

I am using PSPM to analyse skin conductance repsonse. 
I am running a script in Matlab to generate missing epochs and detect artificial spikes (if you want I can append this). While editing I vary the variables "deflection_threshold" and "expand_epoch" for each subject. 

Example:
I generated the following graph. 
Is there anyone who could help me to decide where there is artefact or a true  spike and how to change the parameters to detect the optimal result ?

Best wishes

``

**Comment by dominikbach** [comment]
Hi Cosima
thanks for reaching out. It's difficult to recognise in the plots whether what you see in the data are individual artefacts separated by stretches of good data, or overlaid noise. Is the x-axis in seconds or samples? Can you zoom in more? What happens if you just use the default settings?
Dominik

**Comment by dominikbach** [comment]
Yes, acq data can be directly imported. For acq version < 3.9.0, this does not require any additional packages. For higher acq, it requires a Python installation and the bioread package (https://github.com/njvack/bioread), and is so far only available in the development version (but will be released in version 7.0 soon). See here: https://github.com/bachlab/PsPM/blob/develop/src/pspm_get_acq_python.m

**Comment by KD206** [comment]
Hello, thank you very much for your reply!
I still encountered some problems, and if possible, I hope to get your help.
At present, I can confirm that the format is acq version<3.9.0. My operation steps are shown in the following figure.&nbsp;
And it reports errors，which I show it in the picture.But I am not sure where the problem lies, whether it is a file name issue.





I'm sorry for taking up your time. I would greatly appreciate your help.





君陌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bachlab/PsPM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月18日(星期一) 晚上9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bachlab/PsPM] SCR and PSPM (Issue #329)





 
Yes, acq data can be directly imported. For acq version < 3.9.0, this does not require any additional packages. For higher acq, it requires a Python installation and the bioread package (https://github.com/njvack/bioread), and is so far only available in the development version (but will be released in version 7.0 soon). See here: https://github.com/bachlab/PsPM/blob/develop/src/pspm_get_acq_python.m

**Comment by dominikbach** [comment]
I'm afraid your figures are not displayed on github: https://github.com/bachlab/PsPM/issues/329

Could you please post them again, or email to the address displayed at PsPM startup?

**Comment by KD206** [comment]
Thanks for your reply so much. I have already&nbsp;displayed details at&nbsp;https://github.com/bachlab/PsPM/discussions/801.Thank you for taking the time to assist amidst your busy schedule. Looking forward to your reply.




君陌
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "bachlab/PsPM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bachlab/PsPM] SCR and PSPM (Issue #329)





 
I'm afraid your figures are not displayed on github: #329
 
Could you please post them again, or email to the address displayed at PsPM startup?
