### ISSUE TITLE
pspm_convert_ppu2hb crashes in edge case

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#381]
### Summary

The function crashes in line 165 when ppu_corr turns out to be empty.

### Steps to Reproduce
Will provide data to reproduce directly.

### Expected Results
return empty HB time series

### Actual Results
error in findpeaks

### Technical Info
* PsPM version: develop
* MATLAB version: 2021b

**Comment by teddychao** [comment]
I think this is because the software produce only one available peak based on the rule
> `[~,pis] = findpeaks(data{1}.data, 'MinPeakDistance',60/200*data{1}.header.sr, 'MinPeakProminence',minProm);`

The current output is only one peak, whilst the following analysis wants to calculate the `min_pulse_period` based on the difference
> `min_pulse_period = min(diff(pis));`

It is expectedly that `min_pulse_period` will be calculated as 0... I think maybe the `pspm_convert_ppu2hb` needs to give a warning and stop if only one peak is detected.
