### ISSUE TITLE
help regarding DCM

### ISSUE THREAD

**Issue by AsierJS** [bachlab/PsPM#397]
### Summary

I am new to PSPM and modelling the EDA data so I havea few fundamental questions regarding the analyses of my experiment. The task Ihave to analyse is fear conditioning. To condition the participants, we useelectric shocks that are also recorded in the scr. I have used DCM to analysethe data but, is there a way to filter out the artifact from the electricshocks? On the other hand, I have been testing with this dataand it is not clear to me how to know if the DCM I have done is well done ornot. What should I look at to know that the results are correct? I would also like to know, when you click on the"review model" button and display all trials for one session, whichunits are used in the axes? Finally, I like to know if it is possible to use the functionparfor and, if possible, how can I use it? 

### Technical Info
* PsPM revision ID: 5.1.1
* MATLAB version: 2017b

**Comment by teddychao** [comment]
Hi @AsierJS 
Thanks for posting this issue.
> is there a way to filter out the artifact from the electricshocks?
If it is talking about filter out the noise, I am not quite sure. Could you please give an example about what kind of artefact that is expected to be filtered out? For example, a series of sudden pulses, high-frequency noise, etc.
>  it is not clear to me how to know if the DCM I have done is well done or not.
For dcm processing, it is possible to get the output from dcm through either the GUI or the command line. To verify the results, we normally look at the output plots and check if the information is as expected. I am not sure if the question is referring to a specific step in dcm? If so, please kindly let me know.
> when you click on the"review model" button and display all trials for one session, whichunits are used in the axes?
For all pspm plots, the units of axes are read from headers from datasets. If the unit is not shown properly, it may be a bug to be fixed in the future. We will have a look at it.

I hope it provides some useful information for you. Please feel free to let me know any feedbacks.
Best wishes
teddy
