### ISSUE TITLE
A global variable refering to the GUI plotting window

### ISSUE THREAD

**Issue by jbrochar** [bachlab/PsPM#407]
One eventual issue that users might face is the interference between there plots and PsPM plots.

A way to resolve this would be to adjust the "plot-able" property of the PsPM's windows dynamically.
If every PsPM plotting functions had access to a global variable refering to the main figure to plot, they could switch it to "plot-able", do their things and then switch it back to "unplot-able".

**Comment by teddychao** [comment]
Hi @dominikbach let me explain it here.

1. The reason why users accidentally plot on PsPM UI is, PsPM UI will accept command line so that plots are directly delivered to them.
2. The method of avoiding 1 is to make the property `HandleVisibility` of the component to be "off".
3. When users want to use any UI, either by clicking buttons or using command line, the property `HandleVisibility` must be `callback` rather than `off`.
4. Some functions require user interaction, for example `pspm_display`, because users want to select channels they want to check. When users are selecting, the UI is under the status "waiting". During "waiting", `HandleVisibility` must be `callback`, otherwise it will crash.

Therefore, I can provide three scenarios.
1. If the user would like to use UI only without typing anything on command line, we can set `HandleVisibility` to be `callback` for them.
2.  If the user would like to use command line only without clicking anything, we can set `HandleVisibility` to be `off` for them.
3. If the user wants to use them both, it becomes complicated... Some functions can be in status of `waiting` such as `data editor` for interacting with UI, so `HandleVisibility` shall be `callback`. This also risks because users may want to type command line to plot.

As the solution, I think type 2 users can use script to set `HandleVisibility` to be `off` when they plot (similar to `hold on` command in Matlab) to avoid plotting on UI. Type 3 users need to do this every time when they want. For type 1 users, we shall make the UI always be `HandleVisibility = callback` because they do not type commands.
