### ISSUE TITLE
Normalization of pupil size response

### ISSUE THREAD

**Issue by kirkzmr** [bachlab/PsPM#477]
### Summary
Hi Teddy,

I have one question on the normalization of PSR in GLM. 

I found the the normalization (done by common statistical methods) of non-normalized data generated by GLM is different from the normalized data generated by GLM. May I know the difference of such two models?

Thanks for your time and look forward to your reply.

### Technical Info
* PsPM revision ID: v6.0.0
* MATLAB version: 2022b

**Comment by dominikbach** [comment]
PsPM normalises by z-scoring the filtered time series and computing the amplitude estimates on these data. Since I don't know what normalisation you did, I cannot advise on the difference between the PsPM method and yours. Some different ways of normalising response estimates (for SCR and in the context of fear conditioning) are compared in https://doi.org/10.1016/j.jneumeth.2015.08.009
