### ISSUE TITLE
pspm_dcm incorrectly assign first value of dcm.stats to be always NaN

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#504]
### Summary
Users have reported that `pspm_dcm` incorrectly assign first value of `dcm.stats` to be always `NaN` in the latest develop branch at the moment. This is suspected caused by the incorrect calculation of `proc_subsessions` in `pspm_dcm`, but relevant processing in `pspm_dcm_inv` may be also relevant. This is a critical issue and should be resolved asap.

**Comment by dominikbach** [comment]
The underlying cause is that trials statistics are excluded when there is any NaN data between trial start and trial end (around line 565). This should be changed - users would normally expect that when the NaN data are below the subsession threshold then the trial statistics are reported. This is an improvement, rather than a bug.

**Comment by dominikbach** [comment]
Actually, the problem the user reported is down to an indexing issue - it also happens with no missing data.

**Comment by dominikbach** [comment]
Has been fixed in 6.1
