### ISSUE TITLE
Dependencies do not work on Batch in 6.0 (works fine in 5.1.1)

### ISSUE THREAD

**Issue by dc307** [bachlab/PsPM#507]
### Steps to Reproduce
1. Click on Batch
2. Add a first module (e.g., Import) and fill in settings
3. Add a second module (e.g., Trim) and click File

### Expected Results

A dependency button.

### Actual Results

No dependency button. 

**Error messages:**

Dot indexing is not supported for variables of this type.

Error in cfg_ui_util (line 250)
            smatch(k) = cfg_util('match', job_id, mod_job_id, item_mod_id, sout(k).tgt_spec);

Error in cfg_ui_util (line 305)
                    sout = cfg_ui_util('showvaldeps', ciid{:}, sout);

Error in cfg_ui>local_showvaledit (line 382)
cfg_ui_util('showvaledit', fig, ciid, contents, sout, dflag, [], @()local_valedit_update(obj));

Error in cfg_ui>module_Callback (line 962)
local_showvaledit(hObject);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in cfg_ui (line 53)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)cfg_ui('module_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

### Technical Info
* PsPM version: 6.0.0
* MATLAB version: 2023a

**Comment by teddychao** [comment]
Hi @dc307 

Many thanks for posting the issue.
This is a bug caused by our recent work of improving the UI and migrating to MATLAB mlapp. We have been aware of the reason and tested our solution that will no longer give this warning. We will add this patch to PsPM version 6.1. You may also try the develop branch after we fix this issue.

Best wishes
Teddy
