### ISSUE TITLE
Warning when running Display with full file path

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#718]
### Summary

`pspm_display` works correctly with just the file name but throws a warning when called with full file path (from command line or GUI).

```
>> pspm_display('pspm_PP12.mat')
>> pspm_display('/Users/dominik/Documents/PublicData/Sandbox/pspm_PP12.mat')
Warning: The input to STR2FUNC "/Users/dominik/Documents/PublicData/Sandbox/pspm_PP12.mat" is not a valid
function name. This will generate an error in a future release. 
> In pspm_display (line 32) 
```

**Comment by teddychao** [comment]
Hi @dominikbach 
Thank you for pointing out this issue. Theoretically, this is because the input variable (which is called `varargin{1}` in line 32 of `pspm_display`. `varargin{1}` is a string that represents the input file name or path, so it cannot be used as the input of `str2func`. This issue seems to have been there since PsPM was moved to GitHub, please check [here](https://github.com/bachlab/PsPM/blob/34c8bb388ee23833dcb4892e27b2d443b519c9a2/src/pspm_display.m). I will try to make a theoretical update, since I do not really know why line 32 wants to convert this variable into a function.
Thank you.
Best wishes
Teddy
