### ISSUE TITLE
`pspm_display`  fails in develop branch

### ISSUE THREAD

**Issue by dominikbach** [bachlab/PsPM#744]
### Summary
When a file is selected and I click on "done", the following error occurs (and the file selector remains frozen):
```
No method 'delete' with matching signature found for class 'matlab.ui.control.UIControl'.
 
Error while evaluating UIControl Callback.
```
When I close the file selector by clicking on the top-left cross, the following error message occurs:
Execution of script varargin as a function is not supported:
C:\Program Files\MATLAB\R2021b\toolbox\matlab\lang\varargin.m

```
Error in pspm_display>load_Callback (line 491)
elseif numel(varargin)>1

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in pspm_display (line 48)
  gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)pspm_display('load_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.
```
### Steps to Reproduce
1. Call `pspm_init` and `pspm_display`.
2. Select a file.
3. Click on "done"

### Technical Info
* PsPM version: develop branch, updated this morning.
* MATLAB version: 2021b on Windows.

**Comment by dominikbach** [comment]
Same error for `pspm_review` in develop branch, using models that were computed by the same version.

**Comment by dominikbach** [comment]
On Mac with Matlab 2023a, the error for `pspm_review` is
```
Too many input arguments.
 
Error while evaluating UIControl Callback.
```

**Comment by teddychao** [comment]
I cannot replicate the error that appears after clicking "done" in `pspm_display`. I can see files are imported. I am unsure if this is an error that has been fixed by recent updates.
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/439f3e3b-10ba-4f60-ba70-294ff0cf1abe">

I can see the error of varargin that appears after clicking the cross button. I have added a PR for this issue.
