### ISSUE TITLE
missingepoch_include error in SF module

### ISSUE THREAD

**Issue by DoSlexic** [bachlab/PsPM#810]
### Summary
Hi all,

I'm encountering a persistent error and could use some advice. I've been trying to analyze EDA data using the SF module with epochs defined in a two-column text file with onsets and offsets during music listening sessions. However, I keep getting the following error:

"Unrecognized field name 'missingepoch_include'."

This error points to line 81 in 'pspm_cfg_run_sf.m'. I've also created a .mat file with the variable 'epochs' containing the e x 2 array with seconds as units to use as an alternative to the text file, but I continue to encounter the same error.

I'm at a loss as to what's causing this issue. I've been battling it for a few days now so any guidance would be appreciated.

### Technical Info
* PsPM revision ID:
* Windows 11
* PsPM version: 6.1.2
* MATLAB version: 24.2.0.2712019 (R2024b)

**Comment by dominikbach** [comment]
Thanks for posting this bug in the matlabbatch of PsPM version 6.1.2. This has been fixed in the upcoming version 7.0.0, which is already available through the develop branch. We endeavour to release v7 by mid-January, and in any case we would advise switching to this version, which will be more robust and stable, at the expense of backwards compatibility.

You could 
- wait until mid-January for the release
- git clone the code from the develop version 

Hope this helps!
Dominik
